### ISSUE TITLE
Any example: crash on Linux

### ISSUE THREAD

**Issue by carlOSx64** [unknownue/vulkan-tutorial-rust#36]
I get the following error whenever I try to run an example
```
cargo run --bin 00
```
```
[wayland-client error] Attempted to dispatch unknown opcode 0 for wl_shm, aborting.
```

**Comment by unknownue** [comment]
Everything is ok on my manjaro machine, so I cannot reproduce this problem.
This probably cause by using conflicting version of  `wayland-client` and `winit`. See also https://github.com/Smithay/wayland-rs/issues/357.
Try to upgrade or downgrade version for crate `wayland-client` or `winit` like following:
```toml
# crate version on my machine
[dependencies]
wayland-client    = "=0.23.6"  # Use '=' to specify the exact version you want
wayland-protocols = "=0.23.6"
wayland-sys       = "=0.23.6"
winit             = "=0.20.0"
```
